fix: correct variable name from old_tsamp_initial to old_tstamp_initial in CVE-2026-13122 patch
The patch CVE-2026-13122.patch fixed the variable declaration from
old_tsamp_initial to old_tstamp_initial (adding missing 't'), but did not
update the three usages of this variable. This caused a build error:
  auth_token.c:209:9: error: 'old_tsamp_initial' undeclared

Co-authored-by: hudeng <hudeng@deepin.org>